iteration_with_fail_part2 error at node_count 140, edge_count: 227
error: RunError { error: InternalError("bug: NodeInfo { job_id: \"N4\", state: Output(FinishedUpstreamFailure), history_output: None, last_considered_in_gen: 8 }") }
Jobs: N0(0): Ephemeral(NotReady(Unknown))
N1(1): Output(NotReady(Unknown))
N2(2): Always(Undetermined)
N3(3): Ephemeral(NotReady(Unknown))
N4(4): Output(NotReady(Unknown))


Edges:
(N0(0)->N3(3): Unknown
(N0(0)->N4(4): Unknown
(N1(1)->N2(2): Unknown
(N2(2)->N4(4): Unknown
(N3(3)->N4(4): Unknown


in code: 
g.add_node("N0", JobKind::Ephemeral);
g.add_node("N1", JobKind::Output);
g.add_node("N2", JobKind::Always);
g.add_node("N3", JobKind::Ephemeral);
g.add_node("N4", JobKind::Output);
let edges = vec![
("N3", "N0"), 
("N4", "N0"), 
("N2", "N1"), 
("N4", "N2"), 
("N4", "N3"), 
];
for (a,b) in edges {
            if g.contains_node(a) && g.contains_node(b){
                g.depends_on(a,b);
            }
        }
        ["N1"]